services:
  - type: web
    name: timetable-attendance-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    healthCheckPath: /

databases:
  - name: timetable-attendance-db
    databaseName: timetable_attendance
    user: timetable_user
    plan: free
