services:
  - type: web
    name: timetable-attendance-system
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python deploy_hook.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: timetable-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - "*.py"
        - "requirements.txt"
        - "templates/**"
        - "static/**"
        - "*.yaml"
        - "*.md"
        - "deploy_hook.py"
        - "sync_databases_flask.py"

databases:
  - name: timetable-db
    databaseName: timetable_attendance
    user: timetable_user
    plan: free
